In [35]:
#Altares, Raphael Carlos A.
#NORMALIZATION PROBLEM

import numpy as np

# make a 5x5 matrix with random numbers
X = np.random.random((5, 5))
print("Original Matrix:\n", X)  # Display the original matrix

# find the mean and standard deviation of the matrix
mean = X.mean()  # Calculate the average of all values
std_dev = X.std()  # Calculate how spread out the values are

# normalize the matrix (subtract mean and divide by standard deviation)
X_normalized = (X - mean) / std_dev
print("\nNormalized Matrix:\n", X_normalized)  # Display the normalized matrix

# save the normalized matrix to a file called 'X_normalized.npy'
np.save('X_normalized.npy', X_normalized)

print("\nNormalization complete! The normalized matrix is saved as 'X_normalized.npy'.")



Original Matrix:
 [[0.62948028 0.15624803 0.52574373 0.76541661 0.61437917]
 [0.69400354 0.50530766 0.25183866 0.48092789 0.3846668 ]
 [0.17777893 0.0976557  0.32424627 0.67177855 0.89572309]
 [0.4723703  0.55734549 0.10259798 0.49760881 0.32063765]
 [0.629599   0.82623604 0.67068062 0.4100946  0.83218283]]

Normalized Matrix:
 [[ 0.57326276 -1.51840942  0.11475039  1.17409725  0.50651634]
 [ 0.85845366  0.02442358 -1.09590172 -0.08333427 -0.50880539]
 [-1.42324352 -1.77738575 -0.7758623   0.76021984  1.75004794]
 [-0.12115859  0.25442919 -1.75554104 -0.00960514 -0.7918123 ]
 [ 0.57378753  1.44291727  0.75536705 -0.39641527  1.46920191]]

Normalization complete! The normalized matrix is saved as 'X_normalized.npy'.


In [33]:
#Altares, Raphael Carlos
#Divisible by 3 Problem

import numpy as np

# create a list of numbers from 1 to 100
numbers = np.arange(1, 101)

# square each number 
squares = numbers**2

# reshape the list into a 10x10 matrix
A = squares.reshape(10, 10)

# find elements in the matrix that are divisible by 3
div_by_3 = A[A % 3 == 0]

# save the result to a file named 'div_by_3.npy'
np.save('div_by_3.npy', div_by_3)

# print matrices for confirmation 
print("10x10 Matrix of Squares:\n", A)
print("\nElements Divisible by 3:\n", div_by_3)

print("\nDone! The elements divisible by 3 are saved as 'div_by_3.npy'.")


10x10 Matrix of Squares:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]

Done! The elements divisible by 3 are saved as 'div_by_3.npy'.
